import Head from 'next/head'
import VideoJS, { VideoJsOptions } from '@/components/videojs'
import React from 'react';
import Player from 'video.js/dist/types/player';

export default function Home() {
  const playerRef = React.useRef<Player | null>(null);

  const videoJsOptions: VideoJsOptions = {
    autoplay: true,
    controls: true,
    responsive: true,
    fluid: true,
    sources: [{
      src: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
      type: 'video/mp4'
    }]
  };

  const handlePlayerReady = (player: Player) => {
    playerRef.current = player;

    // You can handle player events here, for example:
    player.on('waiting', () => {
      console.log('player is waiting');
    });

    player.on('dispose', () => {
      console.log('player will dispose');
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>
            videojs sample
          </p>
          <div>
            <a
              href="https://videojs.com/guides/react/"
              target="_blank"
              rel="noopener noreferrer"
            >
              React and Video.js
            </a>
          </div>
        </div>
        <div>
          <VideoJS options={videoJsOptions} onReady={handlePlayerReady} />
        </div>
      </main>
    </>
  )
}
